docking_node:
  ros__parameters:
    distance_pid.kp: 1.0
    distance_pid.ki: 0.1
    distance_pid.kd: 0.01
    angle_pid.kp: 2.0
    angle_pid.ki: 0.2
    angle_pid.kd: 0.02
    source_frame: "base_link"
    P.x: 1.0
    P.y: 1.0
    Q.x: 0.0
    Q.y: 0.0
